apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
        - name: frontend1
          image: ssanchez04/security-front:latest
          ports:
            - containerPort: 80
